site_name: Premier Langage
site_author: Q. Coumes, D. Revuz, M. Cisse, C. Callé
repo_url: https://github.com/PremierLangage/documentationpl
edit_uri: tree/master/docs

nav:
- Bienvenue sur PL coté profs: 'index.md'
- Présentation de PL: 'presentation.md'
- Premier tutoriel: 'premier_tutoriel.md'
- Tutoriels Thématiques: 'tutoriels_thematiques.md'
- Documentations techniques spécifiques: 'documentations_techniques.md'
- Index des clés et Lexique: 'lexique.md'

theme:
    name: 'readthedocs'

markdown_extensions:
  - footnotes
